#!/usr/bin/env ruby

if File.exist?(File.expand_path("../.git", __dir__))
  lib = File.expand_path("../lib", __dir__)

  if !$LOAD_PATH.include?(lib)
    $LOAD_PATH.unshift(lib)
  end
end

require "ahnnotate"
require "ahnnotate/cli"

Ahnnotate::Cli.new(name: File.basename(__FILE__)).run(ARGV)
